---
- name: A playbook that manipulates data from uri
  hosts: localhost

  vars:
    uritouse: "https://api-web.nhle.com/v1/player/8478402/game-log/now"

  tasks:

  - name: Use URI module to send HTTP GET
    ansible.builtin.uri:
      method: GET
      url: "{{ uritouse }}"
    register: results
  - name: Display results
    ansible.builtin.debug:
      msg: "{{ results }}"

