---
- name: Query Trivia API
  hosts: localhost
  gather_facts: no
  vars:
     
     AMOUNT: 10
     DIFFICULTY: easy

  tasks:
    - name: Call custom API module
      trivia_api:
        amount: "{{ AMOUNT }}"
        difficulty: "{{ DIFFICULTY }}"
      register: api_result

    - name: Display API response
      debug:
        msg: "{{ item['question'] }} Answer: {{ item['correct_answer'] }}"
      loop: "{{ api_result.questions }}"


